### ISSUE TITLE
Translation: Validate, flag and filter out strings where the template string variable is changed

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-api#2082]
### Tasks
- [ ] Validate, flag, and filter out strings where the template string variable is changed
- [ ] Add filter to filter out erroneous strings in Admin Panel
- [ ] Warn users of erroneous strings during import

Orginal string: `Cycle {cycle}: {countryName} PER process`
Erroneous strings : `Ciclo {ciclo}: proceso PER de {nombrePaís}`
Correct strings: `Ciclo {cycle}:  proceso PER de {countryName}`

feedback from @steph-gm:

Staging - General Country pages: National Society Overview - Capacity
•	Cycle number or description is not appearing in the boxes in Spanish

_Originally posted by @tovari in https://github.com/IFRCGo/go-web-app/issues/340#issuecomment-2020753197_

**Comment by thenav56** [comment]
@tnagorra to provide regex for validation

**Comment by tnagorra** [comment]
We can use something like this

```javascript
'My {sub} is {obj}'.match(/\{(\w+)\}/g)
```
![image](https://github.com/IFRCGo/go-api/assets/4928045/c2f1d3e8-8eb1-4a98-a632-aecc962836f1)
