### ISSUE TITLE
Local Units and Health Care Data Integration 

### ISSUE THREAD

**Issue by davidmuchatiza** [IFRCGo/go-api#2091]
**Statement of the Problem**
*The professional health services mapping team has been actively engaged in [globally mapping health sites](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Professional%20Health%20Services/Data/Copy%20of%20Master%20Data_Professional%20Health%20Services%20Mapping.xlsx?d=w58db50c3c225441ea46824d4c6d1c8d9&csf=1&web=1&e=92Qiqb) affiliated with National Societies. The project has successfully collected detailed data from 175 National Societies. Simultaneously, the IFRC GO team has been working on incorporating local units for National Societies onto the GO platform, providing a centralized platform for National Societies to manage local unit data. The health sites identified by the Health Mapping Initiative are considered part of the broader local units' dataset, falling under one of the five categories of local units. However, there exists a disparity in data structure, with the health sites' mapping delving deep into attributes associated with health facilities while local units have adopted minimum viable data standards. With the conclusion of the health mapping initiative project, there is consideration for utilizing the GO platform to host this data, enabling users to interact with it on the frontend, which aligns more closely with the goals of the local units project.*

**Solution to Merge the Two Projects**
To integrate these two datasets, the team is proposing the following steps to be undertake:
1. Split the [Health Care data structure](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Professional%20Health%20Services/Documents/Health%20Services%20Data%20Structure.xlsx?d=wa636e90bc68241e9b67c87d54c38d4f2&csf=1&web=1&e=og2So4) into two separate tables: [Table A](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Professional%20Health%20Services/Data/Health%20Services%20Mapping%20Table%20A.xlsx?d=w29d4c798d90c4f2cb0e2bd609d177765&csf=1&web=1&e=g9CQMQ) adopting the [local units' data structure](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Local%20Units/Documents/Local%20Units%20Data%20Dictionary%20-%20Copy.xlsx?d=w65e7033548ce4f0b9781863a6e676ea7&csf=1&web=1&e=8iIq6c), which focuses on basic attribute data, while [Table B](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Professional%20Health%20Services/Data/Health%20Services%20Mapping%20Table%20B.xlsx?d=w70fdb154f1884c1f9f092afa5446dd81&csf=1&web=1&e=MHGlfI) will contain the remaining attributes with health-specific details. These tables will be linked by a common field, **data source ID.**

2. Redesign local unit schema to make a few attributes required and other optional. Additionally, add a **Data Source ID** field to the local units table as a primary key for future reference. Upload Table A contents to the local unit table.

3. Based on feedback from National Societies (NS) and IFRC Geo Call members, there are some changes that need to be made to the local units schema. These changes are not directly related to the integration process but are significant nonetheless: Change field **Level** to **Coverage**; Change field **Level Code** to **Coverage Code**; Change field **Level** (Coverage) contents to as follows: Head Office to **National**, Provincial to **SubNational**, District to **District/Regional**, Ward to **Local**; to change field **Public View** to **Visibility**; And here are the contents of Visibility: **Public, RCRC Movement, IFRC Secretariat & IFRC and NS.** Also note that all these changes are [documented here](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Local%20Units/Documents/Local%20Units%20Data%20Dictionary%20-%20Copy.xlsx?d=w65e7033548ce4f0b9781863a6e676ea7&csf=1&web=1&e=wYsoVD) in the local units data dictionary and on [this to do document](https://ifrcorg.sharepoint.com/:w:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Local%20Units/Documents/Local%20Units%20Backend%20Work.docx?d=w8c4917b33b5b4838849ef2aacf8d3951&csf=1&web=1&e=ry0BVQ) for more clarity.

4. Set up [Table B data schema](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Professional%20Health%20Services/Documents/Health%20Services%20Data%20Structure.xlsx?d=wa636e90bc68241e9b67c87d54c38d4f2&csf=1&web=1&e=8bQdiB), ensuring it is properly linked to the local units table through the data source ID. This may involve significant work to establish the table's structure and relationships. Upload table B contents.

5. Develop a health care units admin page that integrates contents from both the local units table and Table B, where data source IDs match. This page will facilitate centralized management and updates of health facility data on the backend.

6. Implement suggested changes on [wireframes](https://www.figma.com/proto/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?page-id=2%3A68604&type=design&node-id=3856-49130&viewport=2538%2C-1789%2C0.28&t=bOW8frnGS6h41erL-1&scaling=scale-down-width&starting-point-node-id=3856%3A49130&hide-ui=1) to integrate the projects, including the addition of an extended map view. The map view will symbolize different health facility types using provided symbols, [Ambulance Station](https://i.ibb.co/713rxGr/Ambulance-Station.png), [Hospital](https://i.ibb.co/cvm3m3h/Hospital.png), [PHC Centre](https://i.ibb.co/yhYWw9Q/PHC-Centre.png), [Training Facility](https://i.ibb.co/5kY1Hp8/Training-Facility.png), [Others](https://i.ibb.co/C5SdLDV/Others.png), [Pharmacy](https://i.ibb.co/YjYJX91/Pharmacy.png), [Blood Centre](https://i.ibb.co/fCzwY1Y/Blood-Centre.png), [Specialized Services](https://i.ibb.co/Zf0xwhB/Specialized-Services.png) and [Residential Facility](https://i.ibb.co/Yh8cmvZ/Residential-Facility.png).

7. Develop an Edit/Add page on the front end for local units or health facilities. While this may not be an immediate priority, it is essential for future versions to facilitate data maintenance tasks efficiently.

## Development tasks (by DEVs)

- [x] https://github.com/IFRCGo/go-api/issues/2088
- [x] IFRCGo/go-api#2110
- [ ] IFRCGo/go-web-app#856
- [ ] IFRCGo/go-web-app#857
- [ ] IFRCGo/go-api#2100
- [ ] IFRCGo/go-api#2101
- [ ] https://github.com/IFRCGo/go-web-app/issues/823
- [ ] IFRCGo/go-web-app#858
- [ ] https://github.com/IFRCGo/go-web-app/issues/824
- [x] IFRCGo/go-api#2103
- [x] IFRCGo/go-web-app#859
- [x] IFRCGo/go-web-app#871
- [x] #2140
- [x] #2144

**Comment by szabozoltan69** [comment]
Thanks David.
In addition to the overall picture, I was also interested in specific details, such as renaming "level" to "coverage" and other similar technical adjustments. Do you plan to incorporate these changes here?

**Comment by szabozoltan69** [comment]
@davidmuchatiza @samshara @k9845 @tovari – Step 4 is ready: 876 rows data are loaded into table B on Staging:
https://goadmin-stage.ifrc.org/en/admin/local_units/healthdata/
Table A and Table B are not yet connected, it should be done manually on Admin page.
