### ISSUE TITLE
Montandon JWT token Implementation

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-api#2120]
## Previous tickets

1. https://github.com/IFRCGo/go-api/issues/2021
2. https://github.com/IFRCGo/go-api/issues/1982

## Discussions

1. https://github.com/IFRCGo/go-api/discussions/2029

## For May 6, 2024 release
- [x] https://github.com/IFRCGo/go-api/pull/2026
- [x] IFRCGo/go-web-app#890
- [x] IFRCGo/go-web-app#891

## Future
- [ ] #2123

## Issues 
- [x] #2147
