### ISSUE TITLE
[DEPLOYMENT] Elasticsearch indexing fixes

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#631]
@batpad @nanometrenat 

Elasticsearch was giving multiple errors while trying to index records, one of them was it trying to index new records as if they were existing records and fail. This was handled via: https://github.com/IFRCGo/go-api/commit/94773688ea2a202313c1c77a511e93571e9124ea

## TODOs after the deploy to production

- [x] Run `./manage.py index_elasticsearch.py`, which should reindex all records and hopefully fix remaining errors.

- [x] ~~Unset the `ES_HOST` environment variable for staging _(this would make the global search unusable on staging)_~~
**~~OR~~** 
- [x] ~~We should initialize another instance of Elasticsearch dedicated to the staging site, because right now both staging and production use the same Elasticsearch instance which may also lead to (these) errors.~~

- Actually we have separate Elasticsearch instances already for staging and production, so only running the script will be necessary after deployment.

### Changes already on staging but missing from production

- 8134ac93fe811c57be0abb9869314f6d1bf1c960 - https://github.com/IFRCGo/go-frontend/issues/983
- 36bd103f4bade23af498c41578e775264e0723f7
- 94773688ea2a202313c1c77a511e93571e9124ea - https://github.com/IFRCGo/go-frontend/issues/989
- 60512726d4bf7eff2353b5b2f8b179d779a6fc0b - https://github.com/IFRCGo/go-frontend/issues/986

**Comment by nanometrenat** [comment]
@LukeCaley see above re TODOs decision

**Comment by LukeCaley** [comment]
@GregoryHorvath thanks for the resolution and clear options.  Please go ahead and initialize another instance of Elasticsearch dedicated to the staging site.  I am assuming that there is a fairly minimal additional running cost to this and please correct this assumption if wildly wrong.

**Comment by GregoryHorvath** [comment]
> @GregoryHorvath thanks for the resolution and clear options. Please go ahead and initialize another instance of Elasticsearch dedicated to the staging site. I am assuming that there is a fairly minimal additional running cost to this and please correct this assumption if wildly wrong.

Edited the ticket to reflect reality since we figured some things out about the infrastucture with @batpad.

**Comment by batpad** [comment]
Thank you @GregoryHorvath !

The commit that was missing an associated issue was mine: https://github.com/IFRCGo/go-api/commit/36bd103f4bade23af498c41578e775264e0723f7

This is related to the fixes for the field report frontend: https://github.com/IFRCGo/go-frontend/issues/985 - it doesn't fix the whole issue, just the bit about the `phone` field not appearing while editing a field report. The whole issue will not be fixed until we deploy the frontend, but I can definitely guarantee this is a non-breaking change.

I am confident we have tested these on staging and am :+1: on deploying these backend changes to production as soon as possible.

**Comment by GregoryHorvath** [comment]
All deployed and the reindexing ran successfully.

> 8134ac9 - IFRCGo/go-frontend#983
36bd103
9477368 - IFRCGo/go-frontend#989
6051272 - IFRCGo/go-frontend#986

**Comment by nanometrenat** [comment]
Thanks for this team, looks great.  I've commented on 989 with a question.  Most appreciated.
