### ISSUE TITLE
Beautify Deployed Personnel CSV export

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#903]
The CSV export from `/deployments/personnel/all` is quite messy, having all related objects' fields each in a separate column.

## TODO
- [x] Create a prototype version of the export for @mmusori to check
- [ ] Someone to check with users of the API if they're fine with these API changes

**Comment by JonathanGarro** [comment]
Hi @GregoryHorvath - I was asking Daniel about this same issue (saved as a [separate one](https://github.com/IFRCGo/go-api/issues/768) in GitHub) and he pointed out that you're already working on this. Would it be possible to see the prototype in case there was any feedback from my side worth sharing?

**Comment by tovari** [comment]
@thenav56, please also add the following attributes:

- [ ] iso3 codes for both country deployed to and country deployed from
- [ ] deploying organization 
- [ ] host NS
- [ ] status of the deployment, active or closed

**Comment by thenav56** [comment]
Hi, @tovari I am having trouble finding these attributes. Could you help me out by showing the columns in the current [export](https://dsgoproxyapp.azurewebsites.net/deployments/personnel/all) from go?
- deploying organization
- host NS (Is this field report's contact? If yes could you let me know which attributes are required from `ctype, name, title, email, phone`?)
- status of the deployment, active or closed (Is this appeal's status?)

**Comment by thenav56** [comment]
This is now ready for testing at the staging server. https://dsgoproxyapp.azurewebsites.net/deployments/personnel/all

Changes:
 Export structure is changed to include fewer columns. For multiple values, they are aggregated using a comma. Old export can be generated from current prod server https://go.ifrc.org/deployments/personnel/all.
