### ISSUE TITLE
[PROD] PER import function and template

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-api#966]
# TODOs
- [x] ~Export all PER Overview, Form and FormData data from the production DB~
- ~Match the saved answers with the old hard-coded questions~
- ~Create a pattern converting these into the new data-structure~
- ~Create a management command or SQL scripts to import these back in if possible, if not, then create user-friendly sheets which can be used to manually input these back in~
- [ ] Create an Excel/CSV importable template
- [ ] Add Django POST View
- [ ] Add frontend functionality and design
_and / or_
- [ ] Add Django action for Admin users and PER roles

cc @batpad

**Comment by nanometrenat** [comment]
Closing ticket as advised by Stephanie - this old PER is either not relevant any more, or solved because of the new forms/NS preparedness section.  There are other Github tickets related to the new development.
